#! /usr/bin/env python
# encoding utf-8

import glob, os

sources_with_main=\
    ["main.cpp"]

def build(bld):
    """..."""
    print(
        "building at srcpath",
        bld.path.srcpath())
    cpp_files={
        file.split('/')[-1]
        for file in glob.glob(
                bld.path.abspath() + "/*.cpp")}
    includes=\
        ["../../" + x for x in bld.env.INCLUDES_REL] + bld.env.INCLUDES_ABS
    bld.objects(
        source=cpp_files.difference(
            sources_with_main),
        target="libzombie",
        includes=includes,
        cxxflags=bld.env.CXXFLAGS)
    bld.env.append_unique(
        "targets",
        os.path.join(
            bld.path.srcpath(),
            "Zombies"))
    bld.program(
        source="main.cpp",
        use="libzombie",
        stdlib=bld.env.STLIB,
        cxxflags=bld.env.CXXFLAGS,
        includes=incldues,
        lib=bld.env.LDFLAGS_N)
