#! /usr/bin/env python
# encoding: utf-8

import glob, os
sources_with_main= []

def build(bld):
    cpp_files={
        file.split('/')[-1]
        for file in glob.glob(bld.path.abspath() + "/*.cpp")}
    bld.env.append_unique(
        "targets",
        os.path.join(
            bld.path.srcpath(),
            "utils"))
    includes=\
		["../../" + x for x in bld.env.INCLUDES_REL] + bld.env.INCLUDES_ABS
    print(
        "building from {}".format(bld.path.srcpath()),
        "includes from {}".format(includes))
    # bld.objects(
    #     source=cpp_files.difference(
    #         sources_with_main),
    #     target="utils",
    #     includes=includes,
    #     cxxflags=bld.env.CXXFLAGS,
    #     lib=bld.env.LDFLAGS_N)

    bld.stlib(
        source=cpp_files,
        use=["FS"],
        target="utils",
        cxxflags=bld.env.CXXFLAGS,
        includes=includes,
        lib=bld.env.LDFLAGS_N)
