#! /usr/bin/env python
# encoding: utf-8

import glob, os

#DIRS = "tutorial games utils"
DIRS = "tutorial"

def build(bld):
    """..."""
    print(
        "building at",
        bld.path.abspath())
    INCLUDES=\
        ["../" + x for x in bld.env.INCLUDES_REL] + bld.env.INCLUDES_ABS
    print(
        "INCLUDES: {}".format(INCLUDES))
    bld.recurse(DIRS)
